name: Node.js CI

on:
  push:
    branches: ["**"]
    tags: ["**"]
  release:
    types: ["created"]
  pull_request:
    branches: ["**"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Checkout
        run: |
          mkdir -p public/cdn
          git clone https://github.com/sliceofvglife/comics.git public/cdn/comics
      - name: Build
        run: npm run build --if-present
        env:
          CI: true
      - name: Clean
        run: rm -rf out/cdn
      - name: Pack
        run: |
          mkdir -v -p build/web
          cp -r out/* build/web/
          touch build/web/.nojekyll
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        if: github.ref == 'refs/heads/main'
        uses: GuillaumeFalourd/setup-rsync@v1.1
      - name: Deploy to GitHub Pages 🚀
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build/web
